import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'







const inter= Inter({subsets:["latin"]})

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={`${inter.className}`}
      >
      <Header/>
        <main className="min-h-screen">
        {children}</main>
        
        <footer className="bg-blue-50 py-12">
          <div className="container mx-auto px-4 text-gray-400 text-center">
            <p>
              Made with love by mudit
            </p>
            
          </div>
        </footer>
        
      </body>
    </html>
    </ClerkProvider>
  );
}
